# Intro to Recommender Systems Lab

Complete the exercises below to solidify your knowledge and understanding of recommender systems.

For this lab, we are going to be putting together a user similarity based recommender system in a step-by-step fashion. Our data set contains customer grocery purchases, and we will use similar purchase behavior to inform our recommender system. Our recommender system will generate 5 recommendations for each customer based on the purchases they have made.

In [1]:
import pandas as pd
from scipy.spatial.distance import pdist, squareform

In [2]:
data = pd.read_csv('../data/customer_product_sales.csv')

In [3]:
data.head()

,CustomerID,FirstName,LastName,SalesID,ProductID,ProductName,Quantity
0,61288,Rosa,Andersen,134196,229,Bread - Hot Dog Buns,16
1,77352,Myron,Murray,6167892,229,Bread - Hot Dog Buns,20
2,40094,Susan,Stevenson,5970885,229,Bread - Hot Dog Buns,11
3,23548,Tricia,Vincent,6426954,229,Bread - Hot Dog Buns,6
4,78981,Scott,Burch,819094,229,Bread - Hot Dog Buns,20

## Step 1: Create a data frame that contains the total quantity of each product purchased by each customer.

You will need to group by CustomerID and ProductName and then sum the Quantity field.

In [4]:
purchases = data.groupby(['CustomerID', 'ProductName']).agg({'Quantity':'sum'})
purchases.head()

                                          Quantity
CustomerID ProductName
33         Apricots - Dried                      1
           Assorted Desserts                     1
           Bandage - Flexible Neon               1
           Bar Mix - Pina Colada, 355 Ml         1
           Beans - Kidney, Canned                1

## Step 2: Use the `pivot_table` method to create a product by customer matrix.

The rows of the matrix should represent the products, the columns should represent the customers, and the values should be the quantities of each product purchased by each customer. You will also need to replace nulls with zeros, which you can do using the `fillna` method.

In [5]:
purchases_table = pd.pivot_table(purchases, columns = 'CustomerID', index = 'ProductName', fill_value = 0, values = 'Quantity')
purchases_table.head()

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
ProductName,,,,,,,,,,,,,,,,,,,,,
Anchovy Paste - 56 G Tube,0,0,0,0,0,0,0,1,0,0,...,0,25,0,0,0,0,0,0,0,0
"Appetizer - Mini Egg Roll, Shrimp",0,0,0,0,0,0,0,0,0,0,...,25,25,0,0,0,0,0,0,0,0
Appetizer - Mushroom Tart,0,0,0,0,0,0,0,1,0,0,...,25,0,0,0,0,0,0,0,25,0
Appetizer - Sausage Rolls,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,25,25,25,0,25,0
Apricots - Dried,1,0,0,0,1,0,0,0,0,0,...,0,25,0,0,0,0,0,0,0,0

## Step 3: Create a customer similarity matrix using `squareform` and `pdist`. For the distance metric, choose "euclidean."

In [6]:
from scipy.spatial.distance import pdist, squareform

squareform(pdist(purchases_table, metric = 'euclidean'))

array([[  0.        , 279.99642855, 253.66907577, ..., 255.67166444,
        258.0910692 , 278.47800631],
       [279.99642855,   0.        , 271.49953959, ..., 265.7367118 ,
        279.55500353, 286.80655502],
       [253.66907577, 271.49953959,   0.        , ..., 245.27535547,
        253.01580978, 269.43644891],
       ...,
       [255.67166444, 265.7367118 , 245.27535547, ...,   0.        ,
        264.14200726, 268.28343221],
       [258.0910692 , 279.55500353, 253.01580978, ..., 264.14200726,
          0.        , 273.15014186],
       [278.47800631, 286.80655502, 269.43644891, ..., 268.28343221,
        273.15014186,   0.        ]])

## Step 4: Check your results by generating a list of the top 5 most similar customers for a specific CustomerID.

In [34]:
purchases_table2 = pd.DataFrame(1 / (1 + squareform(pdist(purchases_table.T, metric = 'euclidean'))), index = purchases_table.columns, columns = purchases_table.columns)

top_5 = purchases_table2[33].sort_values(ascending = False)[1:6]
top_5

#con purchases_table2[XX] se puede escoger el customerID que sea

CustomerID
264     0.087047
3535    0.087047
3317    0.087047
2503    0.085983
3305    0.085638
Name: 33, dtype: float64

## Step 5: From the data frame you created in Step 1, select the records for the list of similar CustomerIDs you obtained in Step 4.

In [35]:
#similar = purchases.filter(top_5, axis = 1)
#similar

similar = purchases.loc[top_5.index]
similar

                                          Quantity
CustomerID ProductName
264        Apricots - Halves                     1
           Apricots Fresh                        1
           Bacardi Breezer - Tropical            1
           Bagel - Plain                         1
           Banana - Leaves                       1
...                                            ...
3305       Wine - Ej Gallo Sierra Valley         2
           Wine - Pinot Noir Latour              1
           Wine - Redchard Merritt               1
           Wine - White Cab Sauv.on              1
           Yogurt - French Vanilla               1

[270 rows x 1 columns]

## Step 6: Aggregate those customer purchase records by ProductName, sum the Quantity field, and then rank them in descending order by quantity.

This will give you the total number of each product purchased by the 5 most similar customers to the customer you selected in order from most purchased to least.

In [36]:
similar_products = similar.groupby('ProductName').Quantity.sum().sort_values(ascending = False)
similar_products

ProductName
Butter - Unsalted                3
Soup - Campbells Bean Medley     3
Towels - Paper / Kraft           3
Wine - Ej Gallo Sierra Valley    3
Pepper - Black, Whole            3
                                ..
Pepper - White, Ground           1
Pepper - Paprika, Hungarian      1
Pate - Cognac                    1
Pastry - Choclate Baked          1
Anchovy Paste - 56 G Tube        1
Name: Quantity, Length: 218, dtype: int64

## Step 7: Filter the list for products that the chosen customer has not yet purchased and then recommend the top 5 products with the highest quantities that are left.

- Merge the ranked products data frame with the customer product matrix on the ProductName field.
- Filter for records where the chosen customer has not purchased the product.
- Show the top 5 results.

In [45]:
merged_table = purchases_table.merge(similar_products, on = 'ProductName')
filtered_table = merged_table[merged_table[33] == 0].sort_values('Quantity', ascending = False)
filtered_recommendations = filtered_table.nlargest(5, 'Quantity')['Quantity']
filtered_recommendations

#these are the recommended products

ProductName
Wine - Blue Nun Qualitatswein    3
Soup - Campbells Bean Medley     3
Wine - Ej Gallo Sierra Valley    3
Butter - Unsalted                3
Yoghurt Tubes                    2
Name: Quantity, dtype: int64

## Step 8: Now that we have generated product recommendations for a single user, put the pieces together and iterate over a list of all CustomerIDs.

- Create an empty dictionary that will hold the recommendations for all customers.
- Create a list of unique CustomerIDs to iterate over.
- Iterate over the customer list performing steps 4 through 7 for each and appending the results of each iteration to the dictionary you created.

In [47]:
recommendations = {} 
unique_ID = data['CustomerID'].unique()

for ID in unique_ID:
    #Distances 
    purchases_table2 = pd.DataFrame(1 / (1 + squareform(pdist(purchases_table.T, metric = 'euclidean'))), index = purchases_table.columns, columns = purchases_table.columns)
    
    #Similarities 
    top_5 = purchases_table2[ID].sort_values(ascending = False)[1:6]
    similar = purchases.loc[top_5.index]
    similar_products = similar.groupby('ProductName').Quantity.sum().sort_values(ascending = False)
    
    #Not purchased, to recommend 
    merged_table = purchases_table.merge(similar_products, on = 'ProductName')
    filtered_table = merged_table[merged_table[ID] == 0].sort_values('Quantity', ascending = False)
    filtered_recommendations = filtered_table.nlargest(5, 'Quantity')['Quantity']
    
    recommendations[ID] = filtered_recommendations.index

##  Step 9: Store the results in a Pandas data frame. The data frame should a column for Customer ID and then a column for each of the 5 product recommendations for each customer.

In [49]:
pd.DataFrame(recommendations)

,61288,77352,40094,23548,78981,83106,11253,35107,15088,26031,...,25270,17390,97029,38154,74403,49005,41286,85878,68506,3472
0,Chicken - Soup Base,Wine - Valpolicella Masi,Bread - Italian Corn Meal Poly,Squid - Tubes / Tenticles 10/20,Vanilla Beans,Cocoa Butter,Juice - Lime,Bread - French Baquette,Soupfoamcont12oz 112con,Cheese - Mozzarella,...,Beef - Top Sirloin,"Pasta - Penne, Rigate, Dry",Milk - 2%,Rum - Mount Gay Eclipes,Chips Potato Salt Vinegar 43g,"Pasta - Penne, Rigate, Dry",Veal - Inside,Olives - Kalamata,Beef - Ground Medium,Soup - Campbells Bean Medley
1,Jagermeister,Tahini Paste,Puree - Mocha,Pernod,Lettuce - Frisee,"Cheese - Boursin, Garlic / Herbs",Pomello,Bandage - Flexible Neon,Soup Knorr Chili With Beans,"Lemonade - Natural, 591 Ml",...,Grouper - Fresh,Coffee - Hazelnut Cream,Bay Leaf,Cake - Box Window 10x10x2.5,Fenngreek Seed,Browning Caramel Glace,Wasabi Powder,Wine - White Cab Sauv.on,"Veal - Brisket, Provimi,bnls",Wine - Blue Nun Qualitatswein
2,Lime Cordial - Roses,Tuna - Salad Premix,Tuna - Salad Premix,Wanton Wrap,"Yogurt - Blueberry, 175 Gr",Garlic - Peeled,Tomatoes Tear Drop,Bread Crumbs - Panko,Otomegusa Dashi Konbu,Quiche Assorted,...,Eggplant - Asian,Soup Knorr Chili With Beans,"Veal - Inside, Choice",Muffin Mix - Blueberry,Bay Leaf,Tea - Decaf Lipton,"Thyme - Lemon, Fresh",Bread - Calabrese Baguette,Scallops - 10/20,"Pepper - Black, Whole"
3,Macaroons - Two Bite Choc,Chicken - Soup Base,Sherry - Dry,Bread - Raisin Walnut Oval,Cinnamon Buns Sticky,Sauce - Hollandaise,"Potatoes - Instant, Mashed",Wine - Hardys Bankside Shiraz,Wine - Fume Blanc Fetzer,Bananas,...,Soup Knorr Chili With Beans,Rabbit - Whole,Banana Turning,Cheese - Mix,Veal - Sweetbread,"Garlic - Primerba, Paste","Placemat - Scallop, White",Veal - Eye Of Round,"Rosemary - Primerba, Paste",Wine - Ej Gallo Sierra Valley
4,"Water - Mineral, Natural",Isomalt,Beer - Sleemans Cream Ale,Banana Turning,Pop Shoppe Cream Soda,Cheese - Mix,Wine - Blue Nun Qualitatswein,"Lentils - Red, Dry","Cup - 6oz, Foam",Mangoes,...,Wine - Charddonnay Errazuriz,Cheese Cloth No 100,Wine - Vidal Icewine Magnotta,Wine - Gato Negro Cabernet,Isomalt,"Wine - Red, Harrow Estates, Cab",Wonton Wrappers,Wine - Two Oceans Cabernet,"Oregano - Dry, Rubbed",Butter - Unsalted

## Step 10: Change the distance metric used in Step 3 to something other than euclidean (correlation, cityblock, consine, jaccard, etc.). Regenerate the recommendations for all customers and note the differences.

In [50]:
recommendations = {} 
unique_ID = data['CustomerID'].unique()

for ID in unique_ID:
    #Distances 
    purchases_table2 = pd.DataFrame(1 / (1 + squareform(pdist(purchases_table.T, metric = 'cosine'))), index = purchases_table.columns, columns = purchases_table.columns)
    
    #Similarities 
    top_5 = purchases_table2[ID].sort_values(ascending = False)[1:6]
    similar = purchases.loc[top_5.index]
    similar_products = similar.groupby('ProductName').Quantity.sum().sort_values(ascending = False)
    
    #Not purchased, to recommend 
    merged_table = purchases_table.merge(similar_products, on = 'ProductName')
    filtered_table = merged_table[merged_table[ID] == 0].sort_values('Quantity', ascending = False)
    filtered_recommendations = filtered_table.nlargest(5, 'Quantity')['Quantity']
    
    recommendations[ID] = filtered_recommendations.index

In [51]:
pd.DataFrame(recommendations)

,61288,77352,40094,23548,78981,83106,11253,35107,15088,26031,...,25270,17390,97029,38154,74403,49005,41286,85878,68506,3472
0,Jagermeister,Bread - Rye,Juice - V8 Splash,Bagel - Plain,Wine - Blue Nun Qualitatswein,Bouq All Italian - Primerba,"Nut - Chestnuts, Whole",Cheese Cloth No 100,Veal - Sweetbread,Foam Cup 6 Oz,...,"Wine - White, Colubia Cresh",Beef - Inside Round,Milk - 2%,Oil - Shortening - All - Purpose,Clam Nectar,Squid - Tubes / Tenticles 10/20,"Salsify, Organic",Bread - Calabrese Baguette,Flavouring - Orange,"Wine - Red, Colio Cabernet"
1,Wine - Two Oceans Cabernet,Fondant - Icing,Beef - Inside Round,Juice - Orange,Cookies - Assorted,Onions - Vidalia,"Beef - Tenderlion, Center Cut","Wine - Cahors Ac 2000, Clos",Ecolab - Lime - A - Way 4/4 L,Spinach - Baby,...,Scallops - 10/20,Grenadine,Bay Leaf,Foam Cup 6 Oz,Pastry - Raisin Muffin - Mini,"Pepper - White, Ground","Hickory Smoke, Liquid",French Pastry - Mini Chocolate,Longos - Chicken Wings,"Nut - Pistachio, Shelled"
2,Tofu - Firm,Lettuce - Frisee,Truffle Cups - Brown,Veal - Sweetbread,Cheese - Cottage Cheese,Scallops - Live In Shell,Veal - Eye Of Round,Butter - Unsalted,Island Oasis - Mango Daiquiri,Sardines,...,Cup - Translucent 7 Oz Clear,"Pepper - Paprika, Hungarian",Banana Turning,"Spoon - Soup, Plastic","Spoon - Soup, Plastic",Soup Knorr Chili With Beans,Dc Hikiage Hira Huba,Foam Dinner Plate,Tia Maria,Creme De Banane - Marie
3,Appetizer - Sausage Rolls,Bread - French Baquette,"Bread - Roll, Soft White Round",Olives - Stuffed,Baking Powder,Pastry - Choclate Baked,"Soup - Canadian Pea, Dry Mix","Bread - Roll, Canadian Dinner",Milk - 2%,Cookies - Assorted,...,Wasabi Powder,Cheese - Victor Et Berthold,Wine - Vidal Icewine Magnotta,Beef - Montreal Smoked Brisket,Pastry - Butterscotch Baked,Cheese - Bocconcini,Oil - Shortening - All - Purpose,Cheese - Parmesan Grated,"Cheese - Brie, Triple Creme",Napkin White - Starched
4,Dc - Frozen Momji,Pork - Kidney,Cake - Mini Cheesecake,Cinnamon Buns Sticky,Quiche Assorted,"Soup - Canadian Pea, Dry Mix",Wine - Gato Negro Cabernet,"Veal - Brisket, Provimi,bnls",Vaccum Bag 10x13,Cheese - Parmesan Grated,...,Beef - Montreal Smoked Brisket,Wine - Fume Blanc Fetzer,"Veal - Inside, Choice",Cookie Dough - Double,Wine - Magnotta - Belpaese,Barramundi,Banana - Leaves,Wine - Two Oceans Cabernet,Garbag Bags - Black,"Crab - Dungeness, Whole"